// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangedTimePropertyInMovie_And_Added_ApplicationDbContext_To_MovieFormViewmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedTimePropertyInMovie_And_Added_ApplicationDbContext_To_MovieFormViewmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201711190012376_ChangedTimePropertyInMovie_And_Added_ApplicationDbContext_To_MovieFormViewmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
